##
# pulled in some helper methods from the autogenerated websteps
#

def dom_id(model)
  "#" + model.class.to_s.underscore + "_" + model.id.to_s
end

module WithinHelpers
  def with_scope(locator)
    locator ? within(*selector_for(locator)) { yield } : yield
  end
end
World(WithinHelpers)

When /^I follow "([^"]*)"$/ do |link|
  click_link link
end

When /^I click "([^"]*)"$/ do |link|
  click_button link
end

Then /^show me the page$/ do
  save_and_open_page
end
